<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd59a02bdfe0f5c022c959018053abb30
{
    public static $prefixLengthsPsr4 = array (
        'R' => 
        array (
            'Robmu\\DrOnline\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Robmu\\DrOnline\\' => 
        array (
            0 => __DIR__ . '/../..' . '/app',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd59a02bdfe0f5c022c959018053abb30::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd59a02bdfe0f5c022c959018053abb30::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitd59a02bdfe0f5c022c959018053abb30::$classMap;

        }, null, ClassLoader::class);
    }
}
